---
title: "Graphics with ggplot2"
author: "rpdunn"
date: "March 12, 2018"
output: html_document
---
##ggplot2
Data visualization with ggplot2. Also practicing open science principles using github

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo=T)
library(tidyverse)
library(ggthemes)
```

```{r}
myplot <- ggplot(data=mpg, aes(x= displ, y= hwy))

myplot + geom_point(alpha=0.4) +geom_jitter(width=0, height=.05)

 
```


```{r }
ggplot(mpg, aes(x=displ, y = hwy, color = class)) +
  geom_point(alpha=0.4) + geom_jitter(height=.05)
```

Make a scatterplot of highway 'hwy' vs. city 'cty' mileage with points of different sizes representing each 'class' of cars and different colors showing each fuel type 'fl'.  
Size doesn't make much sense for the class variable...
```{r}
myplot2 <- ggplot(data=mpg, aes(x=hwy, y = cty, size=class, color=fl)) +
  geom_point()
myplot2
```


```{r}
myplot3<-ggplot(data=mpg, aes(x=displ, y=hwy)) +
  geom_point(alpha=0.4, color='indianred2')
myplot3
```

```{r}
myplot4<-ggplot(mpg, aes(x=displ, y= hwy, color=class)) + 
  geom_point() +
  facet_wrap(~ manufacturer)
myplot4 +theme_hc()
```

```{r}
myplot5<-ggplot(mpg,aes(x=displ, y=hwy, color=manufacturer)) +
  geom_point() +
  facet_wrap( ~ year) +geom_smooth()
myplot5 + theme_bw()
```

```{r}
myplot6<-ggplot(mpg, aes(x=drv, y=hwy))+
  geom_violin()
myplot6
```

```{r}
myplot7<-ggplot(mpg,aes(x=displ,y=hwy))+
  geom_smooth(method="gam") + geom_point() +
  labs(x="Displacement", y="Highway miles per gallon")
  
t<-theme_minimal()
myplot7 +t+theme(text=element_text(size=16))
```

Now let's make a bar chart
```{r}
myplot8<-ggplot(mpg,aes(x=fl, fill=manufacturer)) + 
  geom_bar()
myplot8
```


Now let's export a plot...
```{r}
myplot9<-ggplot(mpg,aes(x=fl,fill=class)) +
geom_bar(position="dodge")

ggsave("exampleplot.png", plot=myplot9, height= 30, width=15, units="cm")
```

